version: '3.4'

networks:
  backend:

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile-api
    networks:
      - backend
    volumes:
      - ./api:/usr/app/
    command: bash
    tty: true

  test-api:
    build:
      context: .
      dockerfile: ./Dockerfile-test-api
    networks:
      - backend
    command: yarn test

  postgres:
    image: postgres:15.3
    container_name: bdd
    environment:
      POSTGRES_DB : testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpw
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql